const STORAGE_KEY = 'ledgerflow-ap-invoices-v1';
const initialInvoices = [
  {id:'INV-1048',vendor:'Acme Cloud',category:'Software & subscriptions',dueDate:'2026-10-07',amount:4850,approver:'Sarah Chen',status:'pending',submitted:'Today, 09:42',notes:'Annual cloud infrastructure renewal.'},
  {id:'INV-1047',vendor:'Northstar Logistics',category:'Operations',dueDate:'2026-10-09',amount:12640,approver:'Vinod Vijay',status:'pending',submitted:'Yesterday, 16:18',notes:'September freight and delivery services.'},
  {id:'INV-1046',vendor:'Brightline Media',category:'Marketing',dueDate:'2026-10-05',amount:3280,approver:'Michael Torres',status:'rejected',submitted:'Yesterday, 14:05',notes:'Please add the correct cost centre before resubmitting.'},
  {id:'INV-1045',vendor:'Vertex Consulting',category:'Professional services',dueDate:'2026-10-12',amount:8750,approver:'Sarah Chen',status:'pending',submitted:'Oct 01, 11:24',notes:'October finance transformation retainer.'},
  {id:'INV-1044',vendor:'Paper & Post',category:'Operations',dueDate:'2026-10-18',amount:642.5,approver:'Vinod Vijay',status:'approved',submitted:'Sep 30, 15:46',notes:'Office stationery and supplies.'},
  {id:'INV-1043',vendor:'Acme Cloud',category:'Software & subscriptions',dueDate:'2026-10-03',amount:4850,approver:'Sarah Chen',status:'approved',submitted:'Sep 29, 10:12',notes:'Monthly platform subscription.'},
  {id:'INV-1042',vendor:'Greenline Energy',category:'Operations',dueDate:'2026-10-22',amount:1960,approver:'Priya Nair',status:'pending',submitted:'Sep 28, 13:30',notes:'September utilities.'},
  {id:'INV-1041',vendor:'CloudDesk',category:'Software & subscriptions',dueDate:'2026-10-25',amount:1140,approver:'Vinod Vijay',status:'pending',submitted:'Sep 27, 09:15',notes:'Team workspace licences.'},
  {id:'INV-1040',vendor:'Urban Office Co.',category:'Operations',dueDate:'2026-10-28',amount:780,approver:'Vinod Vijay',status:'rejected',submitted:'Sep 26, 16:09',notes:'Duplicate invoice detected.'},
  {id:'INV-1039',vendor:'Westfield Legal',category:'Professional services',dueDate:'2026-10-30',amount:6200,approver:'Sarah Chen',status:'pending',submitted:'Sep 25, 11:08',notes:'Contract review services.'},
  {id:'INV-1038',vendor:'Swift Telecom',category:'Operations',dueDate:'2026-11-02',amount:930,approver:'Priya Nair',status:'approved',submitted:'Sep 24, 14:22',notes:'Business mobile and internet services.'},
  {id:'INV-1037',vendor:'Atlas Security',category:'Operations',dueDate:'2026-11-04',amount:2140,approver:'Michael Torres',status:'pending',submitted:'Sep 23, 10:43',notes:'Quarterly security monitoring.'}
];
let invoices = loadInvoices(); let currentFilter = 'all'; let selectedInvoiceId = null; let decisionAction = null;
const $ = (selector) => document.querySelector(selector); const $$ = (selector) => [...document.querySelectorAll(selector)];
function loadInvoices(){try{const saved=localStorage.getItem(STORAGE_KEY);return saved?JSON.parse(saved):initialInvoices}catch(error){return initialInvoices}}
function saveInvoices(){localStorage.setItem(STORAGE_KEY,JSON.stringify(invoices))}
function money(value){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value)}
function shortDate(date){return new Intl.DateTimeFormat('en-US',{month:'short',day:'2-digit',year:'numeric'}).format(new Date(`${date}T12:00:00`))}
function initials(name){return name.split(' ').map((part)=>part[0]).join('').slice(0,2).toUpperCase()}
function statusLabel(status){return{pending:'Needs review',approved:'Approved',rejected:'Rejected'}[status]||status}
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[character]))}
function visibleInvoices(){const query=$('#invoice-search').value.trim().toLowerCase();return invoices.filter((invoice)=>{const matchesFilter=currentFilter==='all'||invoice.status===currentFilter;const matchesQuery=!query||[invoice.id,invoice.vendor,invoice.category,invoice.approver].join(' ').toLowerCase().includes(query);return matchesFilter&&matchesQuery})}
function renderStats(){const pending=invoices.filter((invoice)=>invoice.status==='pending');const approved=invoices.filter((invoice)=>invoice.status==='approved');const rejected=invoices.filter((invoice)=>invoice.status==='rejected');$('#pending-count').textContent=pending.length;$('.nav-count').textContent=pending.length;$('#pending-value').textContent=money(pending.reduce((sum,invoice)=>sum+Number(invoice.amount),0));$('#pending-vendors').textContent=`${new Set(pending.map((invoice)=>invoice.vendor)).size} vendors`;$('#approved-count').textContent=approved.length+81;$('#all-count').textContent=invoices.length;$('#review-count').textContent=pending.length;$('#approved-tab-count').textContent=approved.length;$('#rejected-count').textContent=rejected.length}
function renderRows(){const rows=$('#invoice-rows');const visible=visibleInvoices();$('#result-count').textContent=`Showing ${visible.length} of ${invoices.length} invoices`,$('#empty-state').classList.toggle('hidden',visible.length>0);rows.innerHTML=visible.map((invoice)=>`<tr data-id="${escapeHtml(invoice.id)}"><td><div class="invoice-cell"><span class="invoice-icon">▤</span><span><strong>${escapeHtml(invoice.id)}</strong><small>${escapeHtml(invoice.submitted)}</small></span></div></td><td><div class="vendor-cell"><strong>${escapeHtml(invoice.vendor)}</strong><small>${escapeHtml(invoice.category)}</small></div></td><td><span class="due-date ${invoice.status==='rejected'?'overdue':''}">${shortDate(invoice.dueDate)}</span></td><td class="amount">${money(invoice.amount)}</td><td><div class="approver"><span class="mini-avatar">${initials(invoice.approver)}</span>${escapeHtml(invoice.approver)}</div></td><td><span class="status-badge status-${invoice.status}">${statusLabel(invoice.status)}</span></td><td><div class="row-actions"><button class="row-action" data-action="view" data-id="${escapeHtml(invoice.id)}" aria-label="View ${escapeHtml(invoice.id)}">↗</button>${invoice.status==='pending'?`<button class="row-action" data-action="approve" data-id="${escapeHtml(invoice.id)}" aria-label="Approve ${escapeHtml(invoice.id)}">✓</button>`:''}</div></td></tr>`).join('')}
function render(){renderStats();renderRows();$$('.tab').forEach((tab)=>{const active=tab.dataset.filter===currentFilter;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',active?'true':'false')})}
function showToast(message,success=true){const toast=$('#toast');toast.textContent=message;toast.classList.toggle('success',success);toast.classList.remove('hidden');window.clearTimeout(showToast.timeout);showToast.timeout=window.setTimeout(()=>toast.classList.add('hidden'),3200)}
function openModal(id){$(`#${id}`).classList.remove('hidden');document.body.style.overflow='hidden'}function closeModal(id){$(`#${id}`).classList.add('hidden');if($$('.modal-backdrop:not(.hidden)').length===0)document.body.style.overflow=''}function getInvoice(id){return invoices.find((invoice)=>invoice.id===id)}
function openDecision(id,action){const invoice=getInvoice(id);if(!invoice)return;selectedInvoiceId=id;decisionAction=action;$('#decision-title').textContent=action==='approve'?'Approve invoice':'Reject invoice';$('#decision-copy').textContent=`${invoice.id} · ${invoice.vendor} · ${money(invoice.amount)}. Add an optional note for the audit trail.`;$('#decision-submit').textContent=action==='approve'?'Approve invoice':'Reject invoice';$('#decision-submit').classList.toggle('danger-button',action==='reject');$('#decision-form').reset();openModal('decision-modal')}
document.addEventListener('click',(event)=>{const target=event.target.closest('[data-action]');if(target){const action=target.dataset.action;if(action==='open-invoice-modal')openModal('invoice-modal');if(action==='close-modal')closeModal('invoice-modal');if(action==='close-decision')closeModal('decision-modal');if(action==='view'){const invoice=getInvoice(target.dataset.id);if(invoice)showToast(`${invoice.id} selected · ${invoice.vendor}`)}if(action==='approve'||action==='reject')openDecision(target.dataset.id,action);if(action==='export'){const header=['Invoice','Vendor','Category','Due date','Amount','Approver','Status'];const csv=[header,...invoices.map((invoice)=>[invoice.id,invoice.vendor,invoice.category,invoice.dueDate,invoice.amount,invoice.approver,invoice.status])].map((row)=>row.map((cell)=>`"${String(cell).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='accounts-payable-invoices.csv';link.click();URL.revokeObjectURL(link.href);showToast('Invoice queue exported')}if(action==='filter')showToast('Filter controls are ready for your approval rules')}const tab=event.target.closest('.tab');if(tab){currentFilter=tab.dataset.filter;render()}if(event.target.classList.contains('modal-backdrop'))closeModal(event.target.id)});
$('#invoice-search').addEventListener('input',renderRows);
$('#invoice-form').addEventListener('submit',(event)=>{event.preventDefault();const form=new FormData(event.target);const invoice={id:form.get('number').trim(),vendor:form.get('vendor').trim(),category:form.get('category'),dueDate:form.get('dueDate'),amount:Number(form.get('amount')),approver:form.get('approver'),status:'pending',submitted:'Just now',notes:form.get('notes').trim()};if(invoices.some((item)=>item.id.toLowerCase()===invoice.id.toLowerCase())){showToast('That invoice number already exists',false);return}invoices=[invoice,...invoices];saveInvoices();render();closeModal('invoice-modal');event.target.reset();showToast(`${invoice.id} submitted for approval`)});
$('#decision-form').addEventListener('submit',(event)=>{event.preventDefault();const invoice=getInvoice(selectedInvoiceId);if(!invoice)return;invoice.status=decisionAction==='approve'?'approved':'rejected';const comment=new FormData(event.target).get('comment').trim();if(comment)invoice.notes=comment;saveInvoices();render();closeModal('decision-modal');showToast(`${invoice.id} ${invoice.status}`)});
document.addEventListener('keydown',(event)=>{if(event.key==='Escape'){closeModal('invoice-modal');closeModal('decision-modal')}});render();
